server {
    listen 443 ssl;
    server_name 10.0.2.15;

    ssl_certificate /etc/ssl/certs/vpn_server.crt;
    ssl_certificate_key /etc/ssl/private/vpn_server.key;

    location / {
        proxy_pass http://127.0.0.1:8099;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}