server {
    #listen 443 ssl;
    listen 80;
    server_name 185.103.254.98;

    #ssl_certificate /etc/ssl/certs/vpn_server.crt;
    #ssl_certificate_key /etc/ssl/private/vpn_server.key;

    location / {
        proxy_pass http://3xui:2053; # Имя контейнера вместо IP
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        # Поддержка WebSocket (необходима для работы панели и некоторых протоколов)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}